"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const SimpleNodeRenderer_1 = require("../src/components/SimpleNodeRenderer");
const ObjectNodeRenderer_1 = require("../src/components/ObjectNodeRenderer");
const ArrayNodeRenderer_1 = require("../src/components/ArrayNodeRenderer");
const RendererContainer = new Map();
RendererContainer.set("SimpleNode", SimpleNodeRenderer_1.SimpleNode);
RendererContainer.set("ObjectNode", ObjectNodeRenderer_1.ObjectNode);
RendererContainer.set("ArrayNode", ArrayNodeRenderer_1.ArrayNode);
exports.default = RendererContainer;
